
-- create account

CREATE TABLE IF NOT EXISTS Account (
ACCOUNT_ID VARCHAR(255) PRIMARY KEY,
BALANCE FLOAT
);

-- create symbol

CREATE TABLE IF NOT EXISTS Symbol (
SYMBOL_ID SERIAL PRIMARY KEY,
SYMBOL_NAME VARCHAR(255) NOT NULL UNIQUE
);

-- create accountShare

CREATE TABLE IF NOT EXISTS AccountShare (
ACCOUNT_ID VARCHAR(255) REFERENCES Account(ACCOUNT_ID),
SYMBOL_ID INT REFERENCES Symbol(SYMBOL_ID),
SHARE FLOAT,
CONSTRAINT PK_AccountShare PRIMARY KEY (ACCOUNT_ID,SYMBOL_ID)
);

-- create contractIDtoAccountID

CREATE TABLE IF NOT EXISTS ContractIDToAccountID (
CONTRACT_ID SERIAL PRIMARY KEY,
ACCOUNT_ID VARCHAR(255) REFERENCES Account(ACCOUNT_ID)
);

-- create contract

CREATE TYPE contract_type AS ENUM ('open', 'part_fill');

CREATE TABLE IF NOT EXISTS Contract (
CONTRACT_ID INT REFERENCES ContractIDToAccountID(CONTRACT_ID),
ACCOUNT_ID VARCHAR(255) REFERENCES Account(ACCOUNT_ID),
SYMBOL_ID INT REFERENCES Symbol(SYMBOL_ID),
PRICE FLOAT,
AMOUNT FLOAT,
MODIFICATION_TIME TIMESTAMP DEFAULT NOW(),
CONTRACT_TYPE contract_type
);

-- create executedContract

CREATE TABLE IF NOT EXISTS ExecutedContract (
CONTRACT_ID INT REFERENCES ContractIDToAccountID(CONTRACT_ID),
ACCOUNT_ID VARCHAR(255) REFERENCES Account(ACCOUNT_ID),
SYMBOL_ID INT REFERENCES Symbol(SYMBOL_ID),
PRICE FLOAT,
AMOUNT FLOAT,
MODIFICATION_TIME TIMESTAMP DEFAULT NOW()
);

-- create cancelledContract

CREATE TABLE IF NOT EXISTS CancelledContract (
CONTRACT_ID INT REFERENCES ContractIDToAccountID(CONTRACT_ID),
ACCOUNT_ID VARCHAR(255) REFERENCES Account(ACCOUNT_ID),
SYMBOL_ID INT REFERENCES Symbol(SYMBOL_ID),
PRICE FLOAT,
AMOUNT FLOAT,
MODIFICATION_TIME TIMESTAMP DEFAULT NOW()
);